- name: current time
  command: date +%D
  register: current_time

- name: debug the time
  debug: msg="Time is = '{{ current_time }}'"


- name: "Provision the VM"
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vmware_new_hostname }}"
    folder: "{{ vmware_folder }}"
    guest_id: "{{ vm_guest_id }}"
    state: "{{ vmware_state }}"
    force: yes
    wait_for_ip_address: yes

    disk:
      - size_gb: "{{ vmware_disk_size }}"
        type: thin
        datastore: "{{ vmware_datastore }}"

    networks:
      - name: "{{ vmware_network }}"
        start_connected: True

    hardware:
      memory_mb: "{{ vmware_ram_mb }}"
      num_cpus: "{{ vm_cpu_count }}"
      num_cpu_cores_per_socket: "{{ vm_core_per_cpu }}"
      hotadd_cpu: True
      hotremove_cpu: True
      hotadd_memory: True
      scsi: paravirtual
      boot_firmware: "efi"

    cdrom:
      type: "iso"
      iso_path: "{{ iso_path_loc }}"
  register: newvminfo

- name: debug newvminfo raw
  debug:
    msg: "RAW INFO: {{ newvminfo }}"
  when: newvminfo is defined
  ignore_errors: true

- name: Gather info from standalone ESXi server having datacenter as 'ha-datacenter'
  vmware_guest_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vmware_datacenter }}"
    validate_certs: no
    uuid: "{{ newvminfo.instance.instance_uuid }}"
  register: vminfo
  until:  vminfo.instance.ipv4 != ''
  retries: 10
  delay: 1
  ignore_errors: yes

- name: debug vminfo raw
  debug:
    msg: "RAW INFO: {{ vminfo }}"
  when: vminfo is defined
  ignore_errors: true

- name: debug vminfo ipv4 information
  debug:
    msg: "{{  vminfo.instance.ipv4  }}"
  when: vminfo is defined
  ignore_errors: true

- name: Wait 300 seconds for port 22  to be active
  wait_for:
    host: "{{ vminfo.instance.hw_eth0.ipv4 }}"
    port: 22
    delay: 60
    state: started
