- include_tasks: threedisks.yml
  when: diskcount == 3
- include_tasks: twodisks.yml
  when: diskcount == 2
- include_tasks: singledisk.yml
  when: diskcount == 1
- include_tasks: custom-iso-deployment.yml
  when:
    - iso_path_loc  != ""
    - coreos_iso == False
- include_tasks: custom-iso-deployment.yml
  when:
    - iso_path_loc  != ""
    - coreos_iso == True
