---
- name: "Deploy new VM called {{ vmware_new_hostname }} with {{ vm_cpu_count }} CPUs, {{ vmware_disk_size }} HDD, {{ vmware_ram_mb }} RAM with {{ vmware_network }} network from {{ vmware_template_name }} template."
  vmware_guest:
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vmware_new_hostname }}"
    template: "{{ vmware_template_name }}"
    wait_for_ip_address: yes
    folder: "{{ vmware_folder }}"
    state: "{{ vmware_state }}"

    disk:
    - size_gb: "{{ vmware_disk_size }}"
      type: thin
      datastore: "{{ vmware_datastore }}"

    hardware:
      memory_mb: "{{ vmware_ram_mb }}"
      num_cpus: "{{ vm_cpu_count }}"

    networks:
    - name: "{{ vmware_network }}"
      start_connected: True


  register: newvminfo
  delegate_to: localhost
  changed_when: False

- name: debug newvminfo raw
  debug:
    msg: "New IP address is {{ newvminfo }}"
  when: newvminfo is defined
  ignore_errors: true

- name: debug newvminfo.instance.ipv4
  debug:
    msg: "New IP address is {{ newvminfo.instance.hw_eth0 | ipv4('address') }}"
  when: newvminfo.instance.ipv4 is defined
  ignore_errors: true

- name: debug newvminfo.instance.ipv4
  debug:
    msg: "New UUID is {{ newvminfo.instance.hw_product_uuid }}"
  when: newvminfo.instance.hw_product_uuid is defined
  ignore_errors: true

- name: Add Additional disk to virtual machine
  disk:
  - size_gb: "{{ vmware_disk_two_size }}"
    type: thin
    datastore: "{{ vmware_datastore }}"
    state: present
  when:  adddisk
