- include_tasks: threedisks.yml
  when: diskcount == 3
- include_tasks: twodisks.yml
  when: diskcount == 2
- include_tasks: singledisk.yml
  when: diskcount == 1
- include_tasks: custom-iso-deployment.yml
  when:
    - iso_path_loc  != "" and coreos_iso == false
- include_tasks: custom-iso-deployment.yml
  when:
    - iso_path_loc  != "" and coreos_iso == true
