- name: current time
  command: date +%D
  register: current_time

- name: debug the time
  debug: msg="Time is = '{{ current_time }}'"


- name: "Provision the VM"
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vmware_new_hostname }}"
    folder: "{{ vmware_folder }}"
    guest_id: "{{ vm_guest_id }}"
    state: present
    force: yes
    wait_for_ip_address: no

    disk:
      - size_gb: "{{ vmware_disk_size }}"
        type: thin
        datastore: "{{ vmware_datastore }}"

    networks:
      - name: "{{ vmware_network }}"
        start_connected: True

    hardware:
      memory_mb: "{{ vmware_ram_mb }}"
      num_cpus: "{{ vm_cpu_count }}"
      num_cpu_cores_per_socket: "{{ vm_core_per_cpu }}"
      memory_reservation_lock: True
      scsi: paravirtual

    customvalues:
      disk.EnableUUID: TRUE
      latency: high

    cdrom:
      type: "iso"
      iso_path: "{{ iso_path_loc }}"
  register: newvminfo

-


#1. govc device.boot -vm bootstrap -order disk,cdrom,ethernet
