---
# if adddisk is false run this playbook
- name: "Deploy new VM called {{ vmware_new_hostname }} with {{ vm_cpu_count }} CPUs, {{ vmware_disk_size }} HDD, {{ vmware_ram_mb }} RAM with {{ vmware_network }} network from {{ vmware_template_name }} template."
  vmware_guest:
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vmware_new_hostname }}"
    template: "{{ vmware_template_name }}"
    wait_for_ip_address: yes
    folder: "{{ vmware_folder }}"
    state: "{{ vmware_state }}"

    disk:
    - size_gb: "{{ vmware_disk_size }}"
      type: thin
      datastore: "{{ vmware_datastore }}"

    hardware:
      memory_mb: "{{ vmware_ram_mb }}"
      num_cpus: "{{ vm_cpu_count }}"

    networks:
    - name: "{{ vmware_network }}"
      start_connected: True

  register: newvminfo
  delegate_to: localhost
  changed_when: False

- name: debug newvminfo raw
  debug:
    msg: "RAW INFO: {{ newvminfo }}"
  when: newvminfo is defined
  ignore_errors: true

- name: debug newvminfo ipv4 information
  debug:
    msg: "{{ newvminfo.instance.ipv4 }}"
  when: newvminfo is defined
  ignore_errors: true

- name: debug newvminfo.instance.hw_eth0.ipaddresses
  debug:
    msg: "RAW INFO: {{ newvminfo.instance.hw_eth0.ipaddresses | ipv4 }}"
  when: foundipv4  == false
  vars:
    foundipv4: "{{ newvminfo.instance.hw_eth0 | ipv4 }}"
  ignore_errors: true

- name: "IP address of the VM to Tower Workflows"
  set_stats:
    data:
      vm_host_name: "{{ vmware_new_hostname }}"
      vm_ip_address: "{{ newvminfo.instance.hw_eth0.ipv4 }}"
  when: foundipv4  != false
  vars:
    foundipv4: "{{ newvminfo.instance.hw_eth0 | ipv4 }}"
  ignore_errors: true

- name: "IP address of the VM to Tower Workflows"
  set_stats:
    data:
      vm_host_name: "{{ vmware_new_hostname }}"
      vm_ip_address: "{{ newvminfo.instance.hw_eth0.ipaddresses  | ipv4 }}"
    when: foundipv4  == false
  vars:
    foundipv4: "{{ newvminfo.instance.hw_eth0 | ipv4 }}"
  ignore_errors: true
